name: Docker Build And Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    env:
      REGISTRY: index.docker.io
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/python-test-proj

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: push
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true

      - name: Generate artifact attestation
        uses: actions/attest@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          predicate-type: 'https://cosign.sigstore.dev/attestation/v1'
          predicate: '{"result":"PASSED"}'
          push-to-registry: true
